# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 600)
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QStatusBar {\n"
"background-color: rgb(37, 37, 38);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QMainWindow {\n"
"background-color: rgb(37, 37, 38);\n"
"border: 1px rgb(37,37,38);\n"
"color: rgb(255, 255, 255);\n"
"}")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background-color: rgb(37, 37, 38);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QWidget .QPushButton {\n"
"border:2px;\n"
"background-color: rgb(89, 89, 97);\n"
"}\n"
"QWidget .QPushButton:hover {\n"
"border:2px;\n"
"background-color: rgb(0, 122, 204);\n"
"}\n"
"\n"
"QLineEdit {\n"
"border:1px solid rgb(67, 67, 70);\n"
"background-color: rgb(51, 51, 55);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:disabled {\n"
"border:1px solid rgb(67, 67, 70);\n"
"background-color: rgb(45, 45, 48);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QWidget .QFrame {\n"
"background-color: rgb(45, 45, 48);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QFrame .QPushButton {\n"
"border:1px solid rgb(83, 83, 85);\n"
"background-color: rgb(63, 63, 70);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QFrame .QPushButton:disabled {\n"
"border: 1px solid rgb(61, 61, 67);\n"
"background-color: rgb(45, 45, 48);\n"
"}\n"
"QFrame .QPushButton:hover {\n"
"background-color: rgb(63, 63, 70);\n"
"border: 1px solid rgb(5, 111, 182);\n"
"}\n"
"\n"
"QMessageBox {\n"
"background-color: rgb(37, 37, 38);\n"
"color: rgb(255, 255, 255);\n"
"font: \'D2Coding\';\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.work_timer = QtWidgets.QLCDNumber(self.centralwidget)
        self.work_timer.setGeometry(QtCore.QRect(300, 260, 281, 131))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        self.work_timer.setFont(font)
        self.work_timer.setAutoFillBackground(False)
        self.work_timer.setObjectName("work_timer")
        self.work_memo = QtWidgets.QTextEdit(self.centralwidget)
        self.work_memo.setGeometry(QtCore.QRect(30, 430, 561, 131))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        self.work_memo.setFont(font)
        self.work_memo.setAutoFillBackground(True)
        self.work_memo.setStyleSheet("border:1px solid rgb(63, 63, 70);")
        self.work_memo.setObjectName("work_memo")
        self.work_start = QtWidgets.QPushButton(self.centralwidget)
        self.work_start.setGeometry(QtCore.QRect(640, 440, 101, 111))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(14)
        self.work_start.setFont(font)
        self.work_start.setAutoFillBackground(False)
        self.work_start.setObjectName("work_start")
        self.work_end = QtWidgets.QPushButton(self.centralwidget)
        self.work_end.setGeometry(QtCore.QRect(770, 440, 101, 111))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(14)
        self.work_end.setFont(font)
        self.work_end.setAutoFillBackground(False)
        self.work_end.setObjectName("work_end")
        self.sttich = QtWidgets.QLabel(self.centralwidget)
        self.sttich.setGeometry(QtCore.QRect(320, 10, 250, 250))
        self.sttich.setObjectName("sttich")
        self.today_label = QtWidgets.QLabel(self.centralwidget)
        self.today_label.setGeometry(QtCore.QRect(620, 10, 271, 131))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.today_label.setFont(font)
        self.today_label.setStyleSheet("border:1px solid rgb(63, 63, 70);")
        self.today_label.setAlignment(QtCore.Qt.AlignCenter)
        self.today_label.setObjectName("today_label")
        self.todo_list_title = QtWidgets.QLabel(self.centralwidget)
        self.todo_list_title.setGeometry(QtCore.QRect(620, 140, 271, 61))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.todo_list_title.setFont(font)
        self.todo_list_title.setStyleSheet("border:1px solid rgb(63, 63, 70);")
        self.todo_list_title.setAlignment(QtCore.Qt.AlignCenter)
        self.todo_list_title.setObjectName("todo_list_title")
        self.set_time_goal_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_time_goal_btn.setGeometry(QtCore.QRect(40, 210, 211, 23))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(12)
        self.set_time_goal_btn.setFont(font)
        self.set_time_goal_btn.setObjectName("set_time_goal_btn")
        self.todo_list = QtWidgets.QListWidget(self.centralwidget)
        self.todo_list.setGeometry(QtCore.QRect(620, 200, 271, 221))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.todo_list.setFont(font)
        self.todo_list.setStyleSheet("border:1px solid rgb(63, 63, 70);")
        self.todo_list.setDragEnabled(True)
        self.todo_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.todo_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.todo_list.setObjectName("todo_list")
        self.today_ach_label = QtWidgets.QLabel(self.centralwidget)
        self.today_ach_label.setGeometry(QtCore.QRect(10, 10, 271, 131))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.today_ach_label.setFont(font)
        self.today_ach_label.setStyleSheet("border:1px solid rgb(63, 63, 70);")
        self.today_ach_label.setAlignment(QtCore.Qt.AlignCenter)
        self.today_ach_label.setObjectName("today_ach_label")
        self.ach_rate_label = QtWidgets.QLabel(self.centralwidget)
        self.ach_rate_label.setGeometry(QtCore.QRect(10, 140, 271, 61))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.ach_rate_label.setFont(font)
        self.ach_rate_label.setStyleSheet("border:1px solid rgb(63, 63, 70);")
        self.ach_rate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ach_rate_label.setObjectName("ach_rate_label")
        self.calendar_img = QtWidgets.QLabel(self.centralwidget)
        self.calendar_img.setGeometry(QtCore.QRect(160, 280, 100, 100))
        self.calendar_img.setObjectName("calendar_img")
        self.statis_img = QtWidgets.QLabel(self.centralwidget)
        self.statis_img.setGeometry(QtCore.QRect(40, 280, 100, 100))
        self.statis_img.setObjectName("statis_img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.work_memo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'D2Coding\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.work_start.setText(_translate("MainWindow", "WORK"))
        self.work_end.setText(_translate("MainWindow", "DONE"))
        self.sttich.setText(_translate("MainWindow", "l"))
        self.today_label.setText(_translate("MainWindow", "2023-01-05\n"
"Monday"))
        self.todo_list_title.setText(_translate("MainWindow", "ToDo List"))
        self.set_time_goal_btn.setText(_translate("MainWindow", "Set Time Goal"))
        self.today_ach_label.setText(_translate("MainWindow", "Today\n"
"Achievement"))
        self.ach_rate_label.setText(_translate("MainWindow", "00 %"))
        self.calendar_img.setText(_translate("MainWindow", "l"))
        self.statis_img.setText(_translate("MainWindow", "l"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
